(package "region-occurrences-highlighter"
         "1.6.2"
         "Mark occurrences of current region (selection)")

(website-url "https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter")
(keywords "convenience")

(package-file "region-occurrences-highlighter.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
